server:
  port: 8081

app:
  jwt:
    secret: TdOGaOOEmgibACqaax9trGLJMu5y6uv4q8pxDxXY4fuPKoGH67sIwQHC6khsubmgB5nzuR-Q5py2hKCdBsH0eg
    expiration-minutes: 60
  admin:
    full-name: System Administrator
    phone: "+10000000000"
    email: admin@konecta.com
    password: ChangeMe123!

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
