// <auto-generated />
using System;
using FinanceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceService.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceService.Models.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_number");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("CardType")
                        .HasColumnType("integer")
                        .HasColumnName("card_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_accounts_email");

                    b.HasIndex("Username")
                        .HasDatabaseName("idx_accounts_username");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("FinanceService.Models.BudgetCycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AnnualTarget")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_target");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("approved_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<decimal?>("LatestForecast")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_forecast");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Owner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("YtdActuals")
                        .HasColumnType("numeric")
                        .HasColumnName("ytd_actuals");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYear")
                        .HasDatabaseName("idx_budget_cycles_year");

                    b.ToTable("budget_cycles");
                });

            modelBuilder.Entity("FinanceService.Models.BudgetSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_amount");

                    b.Property<decimal?>("BudgetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("budget_amount");

                    b.Property<long>("BudgetCycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("budget_cycle_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("ForecastAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("forecast_amount");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCycleId", "Month")
                        .IsUnique();

                    b.ToTable("budget_snapshots");
                });

            modelBuilder.Entity("FinanceService.Models.BudgetStageStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BudgetCycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("budget_cycle_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Owner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCycleId", "Stage")
                        .IsUnique();

                    b.ToTable("budget_stage_status");
                });

            modelBuilder.Entity("FinanceService.Models.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("approved_by");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_ref");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("SubmittedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id");

                    b.HasIndex("Department", "Category", "ExpenseDate")
                        .IsUnique();

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("FinanceService.Models.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("grand_total");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("PdfContentType")
                        .HasColumnType("text")
                        .HasColumnName("pdf_content_type");

                    b.Property<byte[]>("PdfData")
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_data");

                    b.Property<string>("PdfFileName")
                        .HasColumnType("text")
                        .HasColumnName("pdf_file_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("TaxTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_total");

                    b.Property<decimal?>("UntaxedTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("untaxed_total");

                    b.Property<decimal?>("WithholdingTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("withholding_total");

                    b.HasKey("Id");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("FinanceService.Models.InvoiceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("account");

                    b.Property<decimal?>("BaseAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("base_amount");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_percent");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<decimal?>("LineTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("line_total");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Product")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_amount");

                    b.Property<decimal?>("TaxPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_percent");

                    b.Property<decimal?>("WhPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("wh_percent");

                    b.Property<decimal?>("Withholding")
                        .HasColumnType("numeric")
                        .HasColumnName("withholding");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_items");
                });

            modelBuilder.Entity("FinanceService.Models.Payroll", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BaseSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("base_salary");

                    b.Property<decimal?>("Bonuses")
                        .HasColumnType("numeric")
                        .HasColumnName("bonuses");

                    b.Property<decimal?>("Deductions")
                        .HasColumnType("numeric")
                        .HasColumnName("deductions");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<decimal?>("NetSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("net_salary");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period");

                    b.Property<DateOnly?>("ProcessedDate")
                        .HasColumnType("date")
                        .HasColumnName("processed_date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Period")
                        .IsUnique();

                    b.ToTable("payroll");
                });

            modelBuilder.Entity("FinanceService.Models.BudgetSnapshot", b =>
                {
                    b.HasOne("FinanceService.Models.BudgetCycle", "BudgetCycle")
                        .WithMany("Snapshots")
                        .HasForeignKey("BudgetCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetCycle");
                });

            modelBuilder.Entity("FinanceService.Models.BudgetStageStatus", b =>
                {
                    b.HasOne("FinanceService.Models.BudgetCycle", "BudgetCycle")
                        .WithMany("Stages")
                        .HasForeignKey("BudgetCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetCycle");
                });

            modelBuilder.Entity("FinanceService.Models.InvoiceItem", b =>
                {
                    b.HasOne("FinanceService.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FinanceService.Models.BudgetCycle", b =>
                {
                    b.Navigation("Snapshots");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("FinanceService.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
