spring.application.name=api-gateway
server.port=8080
# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Enable actuator endpoints
management.endpoints.web.exposure.include=*

# Gateway Routes
spring.cloud.gateway.discovery.locator.enabled=false

# Auth service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# HR service
spring.cloud.gateway.routes[1].id=hr-service
spring.cloud.gateway.routes[1].uri=http://hr-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/hr/**
