spring.application.name=hr-service
server.port=8083

spring.datasource.url=jdbc:postgresql://hr-postgres:5432/hr_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (match auth-service)
app.jwt.secret=TdOGaOOEmgibACqaax9trGLJMu5y6uv4q8pxDxXY4fuPKoGH67sIwQHC6khsubmgB5nzuR-Q5py2hKCdBsH0eg
app.jwt.expiration=86400000
