services:
  discovery:
    build: ./backend/discovery
    ports: ["8761:8761"]
    networks: [konecta-net]

  config:
    build: ./backend/config
    ports: ["8082:8082"]
    depends_on: [discovery]
    networks: [konecta-net]

  api-gateway:
    build: ./backend/api-geteway
    ports: ["8080:8080"]
    depends_on: [config, discovery]
    networks: [konecta-net]

  auth-postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [konecta-net]

  inventory-postgres:
    image: postgres:16
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - inventory_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [konecta-net]

  hr-postgres:
    image: postgres:16
    container_name: hr-postgres
    environment:
      POSTGRES_DB: hr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - hr_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hr_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [konecta-net]

  auth-service:
    build: ./backend/auth-service
    ports: ["8081:8081"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      auth-postgres:
        condition: service_healthy
      config:
        condition: service_started
      discovery:
        condition: service_started
    networks: [konecta-net]



  hr-service:
    build: ./backend/hr-service
    ports: ["8083:8083"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hr-postgres:5432/hr_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      hr-postgres:
        condition: service_healthy
      config:
        condition: service_started
      discovery:
        condition: service_started
    networks: [konecta-net]

  finance-postgres:
    image: postgres:16
    container_name: finance-postgres
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    volumes:
      - finance_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [konecta-net]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [konecta-net]



  finance-service:
    build: ./backend/finance-service
    ports: ["5288:5288"]
    environment:
      ConnectionStrings__FinanceDb: Host=finance-postgres;Port=5432;Database=finance_db;Username=postgres;Password=1234
      Jwt__Secret: TdOGaOOEmgibACqaax9trGLJMu5y6uv4q8pxDxXY4fuPKoGH67sIwQHC6khsubmgB5nzuR-Q5py2hKCdBsH0eg
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      RabbitMq__VirtualHost: /
      RabbitMq__UseSsl: "false"
      Hr__PrimaryBaseUrl: http://api-gateway:8080/api/hr
    depends_on:
      finance-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      discovery:
        condition: service_started
      config:
        condition: service_started
    networks: [konecta-net]

  inventory-service:
    build: ./backend/inventory-service
    ports: ["8094:8094"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      inventory-postgres:
        condition: service_healthy
      config:
        condition: service_started
      discovery:
        condition: service_started
    networks: [konecta-net]

  frontend:
    build: ./frontend
    ports: ["4200:80"]
    depends_on: [api-gateway]
    networks: [konecta-net]

networks:
  konecta-net:
    driver: bridge

volumes:
  pgdata:
  hr_pgdata:
  finance_pgdata:
  inventory_pgdata:
